const fs = require('fs');
const path = require('path');

// ALL missing keys found from screenshots + code audit
const translations = {
  en: {
    // Checkout missing keys
    pincode: "Pincode",
    enterPincode: "6-digit pincode",
    city: "City",
    enterCity: "Enter city",
    state: "State",
    enterState: "Enter state",
    landmark: "Landmark (Optional)",
    enterLandmark: "Nearby landmark",
    
    // Cart (Navbar) missing keys
    myCart: "My Cart",
    emptyCart: "Your cart is empty",
    addSuppliesDesc: "Add vaccines & supplies from the Marketplace",
    goToMarketplace: "Go to Marketplace",
    items: "items",
    proceedToCheckout: "Proceed to Checkout",
    clearCart: "Clear Cart",
    addBtn: "Add",
    buyNow: "Buy Now",
    
    // Profile missing
    userAccount: "User Account",
    myOrders: "My Orders",
    
    // Disease Detection / Medical Page missing keys
    vetDoctorsPageTitle: "Veterinary Services",
    vetDoctorsPageDesc: "Find trusted veterinary doctors and clinics near you.",
    vetDoctorsDesc: "Find trusted veterinary doctors and clinics near you.",
    aiDiseaseDetection: "AI Disease Detection",
    aiDiseaseDetectionDesc: "Upload a photo of your livestock for instant AI-powered disease analysis.",
    uploadOrPaste: "Drag & drop or paste an image here",
    pressCtrlV: "Press Ctrl+V to paste",
    chooseImage: "Choose Image",
    analyzing: "Analyzing...",
    analyzeDisease: "Analyze Disease",
    detectionResult: "Detection Result",
    allPredictions: "All Predictions",
    recommendation: "Recommendation",
    recommendationText: "Please consult a veterinary doctor immediately for proper treatment.",
    uploadToSeeResults: "Upload an image to see analysis results",
    
    // Medical Dashboard missing keys
    searchVetDoctors: "Search veterinary doctors...",
    addVetDoctor: "Add Doctor",
    addNewVetDoctor: "Register New Veterinary Doctor",
    vetName: "Doctor Name",
    vetNamePlaceholder: "Dr. Full Name",
    vetSpecialization: "Specialization",
    vetSpecializationPlaceholder: "Select specialization",
    vetPhone: "Phone",
    vetPhonePlaceholder: "10-digit phone number",
    vetEmail: "Email",
    vetEmailPlaceholder: "doctor@email.com",
    vetClinicName: "Clinic Name",
    vetClinicNamePlaceholder: "Enter clinic name",
    vetQualification: "Qualification",
    vetQualificationPlaceholder: "e.g. BVSc, MVSc",
    vetExperience: "Experience (years)",
    vetExperiencePlaceholder: "Years of experience",
    vetConsultationFee: "Consultation Fee (₹)",
    vetConsultationFeePlaceholder: "Fee amount",
    vetClinicLocation: "Clinic Location",
    vetCity: "City",
    vetState: "State",
    vetPincode: "Pincode",
    vetLatitude: "Latitude",
    vetLongitude: "Longitude",
    vetPreviousWorkplace: "Previous Work Experience",
    vetPreviousWorkplaceLabel: "Previous Workplace",
    vetPreviousWorkplacePlaceholder: "Name of hospital/clinic",
    vetPreviousWorkplaceDetails: "Work Details",
    vetPreviousWorkplaceDetailsPlaceholder: "Describe your role and experience",
    vetAbout: "About",
    vetAboutPlaceholder: "Brief description about the doctor",
    vetRegisterBtn: "Register Doctor",
    vetLoadingDoctors: "Loading doctors...",
    vetVerified: "Verified",
    vetYearsExp: "{exp} years experience",
    vetPreviousWorkplaceCard: "Previous Workplace",
    vetConsultationFeeLabel: "Consultation Fee",
    loadErrorMsg: "Could not load data. Please try again.",
    specLivestock: "Livestock & Cattle",
    specPoultry: "Poultry",
    specSmallAnimals: "Small Animals",
    specEquine: "Equine",
    specWildlife: "Wildlife",
    specSurgeon: "Veterinary Surgeon",
    specDairy: "Dairy Animal Health",
    specDiseaseSpecialist: "Poultry Disease Specialist",
    specRural: "Rural Veterinary Practice",
    specPublicHealth: "Veterinary Public Health",
    vetClinicsComingSoon: "Clinics management coming soon",
    vetPatientsComingSoon: "Patients management coming soon",
    vetAppointmentsComingSoon: "Appointments management coming soon",
    
    // Awareness additional
    fowlPox: "Fowl Pox",
    fowlPoxSymptoms: "Wart-like lesions on face and comb; yellow patches inside mouth.",
    fowlPoxTreatment: "No specific cure. Apply iodine to lesions and isolate infected birds.",
    fowlPoxPrevention: "Vaccinate chicks and control mosquitoes around the farm.",
    coccidiosis: "Coccidiosis",
    coccidiosisSymptoms: "Bloody diarrhea, ruffled feathers, lethargy, weight loss.",
    coccidiosisTreatment: "Add anti-coccidial drugs to drinking water immediately.",
    coccidiosisPrevention: "Keep litter dry, avoid overcrowding, use medicated feed.",
    
    // Disease detection names
    diseaseHealthy: "Healthy",
    diseaseCoccidiosis: "Coccidiosis",
    diseaseNewCastle: "Newcastle Disease",
    diseaseSalmonella: "Salmonella",
    
    // Home hero
    heroTitle1: "Smarter Livestock Care",
    heroTitle2: "Starts Here",
    heroSubtitle: "Keep your cattle and poultry healthy with simple, smart monitoring. AgroArmor provides the precision tools you need for modern farming.",
  },
  hi: {
    pincode: "पिनकोड",
    enterPincode: "6 अंकों का पिनकोड",
    city: "शहर",
    enterCity: "शहर दर्ज करें",
    state: "राज्य",
    enterState: "राज्य दर्ज करें",
    landmark: "लैंडमार्क (वैकल्पिक)",
    enterLandmark: "पास का लैंडमार्क",
    myCart: "मेरी कार्ट",
    emptyCart: "आपकी कार्ट खाली है",
    addSuppliesDesc: "मार्केटप्लेस से टीके और सामग्री जोड़ें",
    goToMarketplace: "मार्केटप्लेस पर जाएं",
    items: "आइटम",
    proceedToCheckout: "चेकआउट पर जाएं",
    clearCart: "कार्ट खाली करें",
    addBtn: "जोड़ें",
    buyNow: "अभी खरीदें",
    userAccount: "उपयोगकर्ता खाता",
    myOrders: "मेरे ऑर्डर",
    vetDoctorsPageTitle: "पशु चिकित्सा सेवाएं",
    vetDoctorsPageDesc: "अपने पास विश्वसनीय पशु चिकित्सक और क्लीनिक खोजें।",
    vetDoctorsDesc: "अपने पास विश्वसनीय पशु चिकित्सक और क्लीनिक खोजें।",
    aiDiseaseDetection: "AI रोग पहचान",
    aiDiseaseDetectionDesc: "तत्काल AI-संचालित रोग विश्लेषण के लिए अपने पशुओं की तस्वीर अपलोड करें।",
    uploadOrPaste: "यहां खींचें और छोड़ें या चित्र पेस्ट करें",
    pressCtrlV: "पेस्ट करने के लिए Ctrl+V दबाएं",
    chooseImage: "चित्र चुनें",
    analyzing: "विश्लेषण हो रहा है...",
    analyzeDisease: "रोग का विश्लेषण करें",
    detectionResult: "पहचान का परिणाम",
    allPredictions: "सभी भविष्यवाणियां",
    recommendation: "सिफारिश",
    recommendationText: "कृपया उचित उपचार के लिए तुरंत पशु चिकित्सक से संपर्क करें।",
    uploadToSeeResults: "विश्लेषण परिणाम देखने के लिए चित्र अपलोड करें",
    searchVetDoctors: "पशु चिकित्सक खोजें...",
    addVetDoctor: "डॉक्टर जोड़ें",
    addNewVetDoctor: "नए पशु चिकित्सक का पंजीकरण",
    vetName: "डॉक्टर का नाम",
    vetNamePlaceholder: "डॉ. पूरा नाम",
    vetSpecialization: "विशेषज्ञता",
    vetSpecializationPlaceholder: "विशेषज्ञता चुनें",
    vetPhone: "फ़ोन",
    vetPhonePlaceholder: "10 अंकों का फ़ोन नंबर",
    vetEmail: "ईमेल",
    vetEmailPlaceholder: "doctor@email.com",
    vetClinicName: "क्लीनिक का नाम",
    vetClinicNamePlaceholder: "क्लीनिक का नाम दर्ज करें",
    vetQualification: "योग्यता",
    vetQualificationPlaceholder: "उदा. BVSc, MVSc",
    vetExperience: "अनुभव (वर्ष)",
    vetExperiencePlaceholder: "अनुभव के वर्ष",
    vetConsultationFee: "परामर्श शुल्क (₹)",
    vetConsultationFeePlaceholder: "शुल्क राशि",
    vetClinicLocation: "क्लीनिक का स्थान",
    vetCity: "शहर",
    vetState: "राज्य",
    vetPincode: "पिनकोड",
    vetLatitude: "अक्षांश",
    vetLongitude: "देशांतर",
    vetPreviousWorkplace: "पिछला कार्य अनुभव",
    vetPreviousWorkplaceLabel: "पिछला कार्यस्थल",
    vetPreviousWorkplacePlaceholder: "अस्पताल/क्लीनिक का नाम",
    vetPreviousWorkplaceDetails: "कार्य विवरण",
    vetPreviousWorkplaceDetailsPlaceholder: "अपनी भूमिका और अनुभव का वर्णन करें",
    vetAbout: "परिचय",
    vetAboutPlaceholder: "डॉक्टर के बारे में संक्षिप्त विवरण",
    vetRegisterBtn: "डॉक्टर पंजीकृत करें",
    vetLoadingDoctors: "डॉक्टर लोड हो रहे हैं...",
    vetVerified: "सत्यापित",
    vetYearsExp: "{exp} वर्ष अनुभव",
    vetPreviousWorkplaceCard: "पिछला कार्यस्थल",
    vetConsultationFeeLabel: "परामर्श शुल्क",
    loadErrorMsg: "डेटा लोड नहीं हो सका। कृपया पुनः प्रयास करें।",
    specLivestock: "पशुधन और मवेशी",
    specPoultry: "मुर्गी पालन",
    specSmallAnimals: "छोटे जानवर",
    specEquine: "घोड़े",
    specWildlife: "वन्यजीव",
    specSurgeon: "पशु चिकित्सा सर्जन",
    specDairy: "डेयरी पशु स्वास्थ्य",
    specDiseaseSpecialist: "मुर्गी रोग विशेषज्ञ",
    specRural: "ग्रामीण पशु चिकित्सा",
    specPublicHealth: "पशु चिकित्सा सार्वजनिक स्वास्थ्य",
    vetClinicsComingSoon: "क्लीनिक प्रबंधन जल्द आ रहा है",
    vetPatientsComingSoon: "रोगी प्रबंधन जल्द आ रहा है",
    vetAppointmentsComingSoon: "अपॉइंटमेंट प्रबंधन जल्द आ रहा है",
    diseaseHealthy: "स्वस्थ",
    diseaseCoccidiosis: "कॉक्सीडायोसिस",
    diseaseNewCastle: "न्यूकैसल रोग",
    diseaseSalmonella: "साल्मोनेला",
  },
  bn: {
    pincode: "পিনকোড",
    enterPincode: "৬ সংখ্যার পিনকোড",
    city: "শহর",
    enterCity: "শহর লিখুন",
    state: "রাজ্য",
    enterState: "রাজ্য লিখুন",
    landmark: "ল্যান্ডমার্ক (ঐচ্ছিক)",
    enterLandmark: "কাছের ল্যান্ডমার্ক",
    myCart: "আমার কার্ট",
    emptyCart: "আপনার কার্ট খালি",
    addSuppliesDesc: "মার্কেটপ্লেস থেকে টিকা এবং সরবরাহ যোগ করুন",
    goToMarketplace: "মার্কেটপ্লেসে যান",
    items: "আইটেম",
    proceedToCheckout: "চেকআউটে এগিয়ে যান",
    clearCart: "কার্ট খালি করুন",
    addBtn: "যোগ",
    buyNow: "এখনই কিনুন",
    userAccount: "ব্যবহারকারী অ্যাকাউন্ট",
    myOrders: "আমার অর্ডার",
    vetDoctorsPageTitle: "পশুচিকিৎসা সেবা",
    vetDoctorsPageDesc: "আপনার কাছে বিশ্বস্ত পশুচিকিৎসক এবং ক্লিনিক খুঁজুন।",
    vetDoctorsDesc: "আপনার কাছে বিশ্বস্ত পশুচিকিৎসক এবং ক্লিনিক খুঁজুন।",
    aiDiseaseDetection: "AI রোগ সনাক্তকরণ",
    aiDiseaseDetectionDesc: "তাৎক্ষণিক AI বিশ্লেষণের জন্য আপনার পশুদের ছবি আপলোড করুন।",
    uploadOrPaste: "এখানে টেনে আনুন বা ছবি পেস্ট করুন",
    pressCtrlV: "পেস্ট করতে Ctrl+V চাপুন",
    chooseImage: "ছবি নির্বাচন করুন",
    analyzing: "বিশ্লেষণ চলছে...",
    analyzeDisease: "রোগ বিশ্লেষণ করুন",
    detectionResult: "সনাক্তকরণ ফলাফল",
    allPredictions: "সমস্ত পূর্বাভাস",
    recommendation: "সুপারিশ",
    recommendationText: "অনুগ্রহ করে যথাযথ চিকিৎসার জন্য অবিলম্বে পশুচিকিৎসকের সাথে যোগাযোগ করুন।",
    uploadToSeeResults: "বিশ্লেষণ ফলাফল দেখতে ছবি আপলোড করুন",
    searchVetDoctors: "পশুচিকিৎসক খুঁজুন...",
    addVetDoctor: "ডাক্তার যোগ করুন",
    addNewVetDoctor: "নতুন পশুচিকিৎসক নিবন্ধন",
    vetName: "ডাক্তারের নাম",
    vetNamePlaceholder: "ডাঃ পুরো নাম",
    vetSpecialization: "বিশেষত্ব",
    vetSpecializationPlaceholder: "বিশেষত্ব নির্বাচন করুন",
    vetPhone: "ফোন",
    vetPhonePlaceholder: "১০ সংখ্যার ফোন নম্বর",
    vetEmail: "ইমেইল",
    vetEmailPlaceholder: "doctor@email.com",
    vetClinicName: "ক্লিনিকের নাম",
    vetClinicNamePlaceholder: "ক্লিনিকের নাম লিখুন",
    vetQualification: "যোগ্যতা",
    vetQualificationPlaceholder: "যেমন BVSc, MVSc",
    vetExperience: "অভিজ্ঞতা (বছর)",
    vetExperiencePlaceholder: "অভিজ্ঞতার বছর",
    vetConsultationFee: "পরামর্শ ফি (₹)",
    vetConsultationFeePlaceholder: "ফি পরিমাণ",
    vetClinicLocation: "ক্লিনিকের অবস্থান",
    vetCity: "শহর",
    vetState: "রাজ্য",
    vetPincode: "পিনকোড",
    vetLatitude: "অক্ষাংশ",
    vetLongitude: "দ্রাঘিমাংশ",
    vetPreviousWorkplace: "পূর্ববর্তী কর্ম অভিজ্ঞতা",
    vetPreviousWorkplaceLabel: "পূর্ববর্তী কর্মস্থল",
    vetPreviousWorkplacePlaceholder: "হাসপাতাল/ক্লিনিকের নাম",
    vetPreviousWorkplaceDetails: "কাজের বিবরণ",
    vetPreviousWorkplaceDetailsPlaceholder: "আপনার ভূমিকা এবং অভিজ্ঞতা বর্ণনা করুন",
    vetAbout: "পরিচিতি",
    vetAboutPlaceholder: "ডাক্তার সম্পর্কে সংক্ষিপ্ত বিবরণ",
    vetRegisterBtn: "ডাক্তার নিবন্ধন করুন",
    vetLoadingDoctors: "ডাক্তার লোড হচ্ছে...",
    vetVerified: "যাচাইকৃত",
    vetYearsExp: "{exp} বছরের অভিজ্ঞতা",
    vetPreviousWorkplaceCard: "পূর্ববর্তী কর্মস্থল",
    vetConsultationFeeLabel: "পরামর্শ ফি",
    loadErrorMsg: "ডেটা লোড করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    specLivestock: "পশুধন এবং গবাদিপশু",
    specPoultry: "মুরগি পালন",
    specSmallAnimals: "ছোট প্রাণী",
    specEquine: "ঘোড়া",
    specWildlife: "বন্যপ্রাণী",
    specSurgeon: "পশু চিকিৎসা সার্জন",
    specDairy: "দুগ্ধ পশু স্বাস্থ্য",
    specDiseaseSpecialist: "মুরগি রোগ বিশেষজ্ঞ",
    specRural: "গ্রামীণ পশু চিকিৎসা",
    specPublicHealth: "পশু চিকিৎসা জনস্বাস্থ্য",
    vetClinicsComingSoon: "ক্লিনিক ব্যবস্থাপনা শীঘ্রই আসছে",
    vetPatientsComingSoon: "রোগী ব্যবস্থাপনা শীঘ্রই আসছে",
    vetAppointmentsComingSoon: "অ্যাপয়েন্টমেন্ট ব্যবস্থাপনা শীঘ্রই আসছে",
    diseaseHealthy: "সুস্থ",
    diseaseCoccidiosis: "ককসিডিওসিস",
    diseaseNewCastle: "রানীক্ষেত রোগ",
    diseaseSalmonella: "সালমোনেলা",
  },
  te: {
    pincode: "పిన్‌కోడ్",
    enterPincode: "6 అంకెల పిన్‌కోడ్",
    city: "నగరం",
    enterCity: "నగరం నమోదు చేయండి",
    state: "రాష్ట్రం",
    enterState: "రాష్ట్రం నమోదు చేయండి",
    landmark: "ల్యాండ్‌మార్క్ (ఐచ్ఛికం)",
    enterLandmark: "సమీపంలోని ల్యాండ్‌మార్క్",
    myCart: "నా కార్ట్",
    emptyCart: "మీ కార్ట్ ఖాళీగా ఉంది",
    addSuppliesDesc: "మార్కెట్‌ప్లేస్ నుండి టీకాలు & సరఫరాలను జోడించండి",
    goToMarketplace: "మార్కెట్‌ప్లేస్‌కు వెళ్ళండి",
    items: "వస్తువులు",
    proceedToCheckout: "చెక్అవుట్‌కు వెళ్ళండి",
    clearCart: "కార్ట్ క్లియర్ చేయండి",
    addBtn: "జోడించు",
    buyNow: "ఇప్పుడే కొనుగోలు చేయండి",
    userAccount: "వినియోగదారు ఖాతా",
    myOrders: "నా ఆర్డర్‌లు",
    vetDoctorsPageTitle: "పశువైద్య సేవలు",
    vetDoctorsPageDesc: "మీ సమీపంలో నమ్మదగిన పశువైద్యులను మరియు క్లినిక్‌లను కనుగొనండి.",
    vetDoctorsDesc: "మీ సమీపంలో నమ్మదగిన పశువైద్యులను మరియు క్లినిక్‌లను కనుగొనండి.",
    aiDiseaseDetection: "AI వ్యాధి గుర్తింపు",
    aiDiseaseDetectionDesc: "తక్షణ AI వ్యాధి విశ్లేషణ కోసం మీ పశువుల ఫోటో అప్‌లోడ్ చేయండి.",
    uploadOrPaste: "ఇక్కడ డ్రాగ్ & డ్రాప్ చేయండి లేదా చిత్రం పేస్ట్ చేయండి",
    pressCtrlV: "పేస్ట్ చేయడానికి Ctrl+V నొక్కండి",
    chooseImage: "చిత్రం ఎంచుకోండి",
    analyzing: "విశ్లేషిస్తోంది...",
    analyzeDisease: "వ్యాధిని విశ్లేషించండి",
    detectionResult: "గుర్తింపు ఫలితం",
    allPredictions: "అన్ని అంచనాలు",
    recommendation: "సిఫార్సు",
    recommendationText: "సరైన చికిత్స కోసం వెంటనే పశువైద్యుడిని సంప్రదించండి.",
    uploadToSeeResults: "విశ్లేషణ ఫలితాలను చూడటానికి చిత్రం అప్‌లోడ్ చేయండి",
    searchVetDoctors: "పశువైద్యులను వెతకండి...",
    addVetDoctor: "డాక్టర్‌ను జోడించండి",
    addNewVetDoctor: "కొత్త పశువైద్యుడిని నమోదు చేయండి",
    vetRegisterBtn: "డాక్టర్‌ను నమోదు చేయండి",
    vetLoadingDoctors: "డాక్టర్‌లను లోడ్ చేస్తోంది...",
    vetVerified: "ధృవీకరించబడింది",
    loadErrorMsg: "డేటా లోడ్ కాలేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    vetClinicsComingSoon: "క్లినిక్ నిర్వహణ త్వరలో వస్తుంది",
    vetPatientsComingSoon: "రోగి నిర్వహణ త్వరలో వస్తుంది",
    vetAppointmentsComingSoon: "అపాయింట్‌మెంట్ నిర్వహణ త్వరలో వస్తుంది",
    diseaseHealthy: "ఆరోగ్యంగా ఉంది",
    diseaseCoccidiosis: "కాక్సిడియోసిస్",
    diseaseNewCastle: "కొత్తకోట వ్యాధి",
    diseaseSalmonella: "సాల్మొనెల్లా",
  },
  ta: {
    pincode: "பின்கோட்",
    enterPincode: "6 இலக்க பின்கோட்",
    city: "நகரம்",
    enterCity: "நகரத்தை உள்ளிடவும்",
    state: "மாநிலம்",
    enterState: "மாநிலத்தை உள்ளிடவும்",
    landmark: "அடையாளம் (விரும்பினால்)",
    enterLandmark: "அருகிலுள்ள அடையாளம்",
    myCart: "எனது வண்டி",
    emptyCart: "உங்கள் வண்டி காலியாக உள்ளது",
    addSuppliesDesc: "சந்தையிலிருந்து தடுப்பூசி மற்றும் பொருட்களை சேர்க்கவும்",
    goToMarketplace: "சந்தைக்கு செல்லவும்",
    items: "பொருட்கள்",
    proceedToCheckout: "செக்அவுட்டிற்கு செல்லவும்",
    clearCart: "வண்டியை காலி செய்",
    addBtn: "சேர்",
    buyNow: "இப்போது வாங்கவும்",
    userAccount: "பயனர் கணக்கு",
    myOrders: "எனது ஆர்டர்கள்",
    vetDoctorsPageTitle: "கால்நடை மருத்துவ சேவைகள்",
    vetDoctorsPageDesc: "உங்கள் அருகிலுள்ள நம்பகமான கால்நடை மருத்துவர்களைக் கண்டறியுங்கள்.",
    vetDoctorsDesc: "உங்கள் அருகிலுள்ள நம்பகமான கால்நடை மருத்துவர்களைக் கண்டறியுங்கள்.",
    aiDiseaseDetection: "AI நோய் கண்டறிதல்",
    aiDiseaseDetectionDesc: "உடனடி AI நோய் பகுப்பாய்வுக்கு உங்கள் கால்நடை புகைப்படத்தை பதிவேற்றவும்.",
    uploadOrPaste: "இங்கே இழுத்து விடவும் அல்லது படத்தை ஒட்டவும்",
    pressCtrlV: "ஒட்ட Ctrl+V அழுத்தவும்",
    chooseImage: "படத்தைத் தேர்ந்தெடுக்கவும்",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    analyzeDisease: "நோயை பகுப்பாய்வு செய்யவும்",
    detectionResult: "கண்டறிதல் முடிவு",
    allPredictions: "அனைத்து கணிப்புகள்",
    recommendation: "பரிந்துரை",
    recommendationText: "சரியான சிகிச்சைக்கு உடனடியாக கால்நடை மருத்துவரை அணுகவும்.",
    uploadToSeeResults: "பகுப்பாய்வு முடிவுகளைக் காண படத்தை பதிவேற்றவும்",
    searchVetDoctors: "கால்நடை மருத்துவர்களை தேடுங்கள்...",
    addVetDoctor: "மருத்துவரைச் சேர்க்கவும்",
    addNewVetDoctor: "புதிய கால்நடை மருத்துவரை பதிவு செய்யவும்",
    vetRegisterBtn: "மருத்துவரை பதிவு செய்யவும்",
    vetLoadingDoctors: "மருத்துவர்கள் ஏற்றப்படுகின்றன...",
    vetVerified: "சரிபார்க்கப்பட்டது",
    loadErrorMsg: "தரவை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    vetClinicsComingSoon: "கிளினிக் மேலாண்மை விரைவில் வரும்",
    vetPatientsComingSoon: "நோயாளி மேலாண்மை விரைவில் வரும்",
    vetAppointmentsComingSoon: "சந்திப்பு மேலாண்மை விரைவில் வரும்",
    diseaseHealthy: "ஆரோக்கியமானது",
    diseaseCoccidiosis: "காக்சிடியோசிஸ்",
    diseaseNewCastle: "வெள்ளைக்கழிச்சல் நோய்",
    diseaseSalmonella: "சால்மோனெல்லா",
  },
  kn: {
    pincode: "ಪಿನ್‌ಕೋಡ್",
    enterPincode: "6 ಅಂಕಿಯ ಪಿನ್‌ಕೋಡ್",
    city: "ನಗರ",
    enterCity: "ನಗರವನ್ನು ನಮೂದಿಸಿ",
    state: "ರಾಜ್ಯ",
    enterState: "ರಾಜ್ಯವನ್ನು ನಮೂದಿಸಿ",
    landmark: "ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್ (ಐಚ್ಛಿಕ)",
    enterLandmark: "ಹತ್ತಿರದ ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್",
    myCart: "ನನ್ನ ಕಾರ್ಟ್",
    emptyCart: "ನಿಮ್ಮ ಕಾರ್ಟ ಖಾಲಿಯಾಗಿದೆ",
    addSuppliesDesc: "ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್‌ನಿಂದ ಲಸಿಕೆ ಮತ್ತು ಸರಬರಾಜುಗಳನ್ನು ಸೇರಿಸಿ",
    goToMarketplace: "ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್‌ಗೆ ಹೋಗಿ",
    items: "ಐಟಂಗಳು",
    proceedToCheckout: "ಚೆಕ್ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ",
    clearCart: "ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಿ",
    addBtn: "ಸೇರಿಸು",
    buyNow: "ಈಗ ಖರೀದಿಸಿ",
    userAccount: "ಬಳಕೆದಾರ ಖಾತೆ",
    myOrders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    vetDoctorsPageTitle: "ಪಶುವೈದ್ಯ ಸೇವೆಗಳು",
    vetDoctorsPageDesc: "ನಿಮ್ಮ ಹತ್ತಿರದ ನಂಬಿಗಸ್ತ ಪಶುವೈದ್ಯರನ್ನು ಹುಡುಕಿ.",
    vetDoctorsDesc: "ನಿಮ್ಮ ಹತ್ತಿರದ ನಂಬಿಗಸ್ತ ಪಶುವೈದ್ಯರನ್ನು ಹುಡುಕಿ.",
    aiDiseaseDetection: "AI ರೋಗ ಪತ್ತೆ",
    aiDiseaseDetectionDesc: "ತಕ್ಷಣ AI ರೋಗ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಜಾನುವಾರುಗಳ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    uploadOrPaste: "ಇಲ್ಲಿ ಡ್ರ್ಯಾಗ್ & ಡ್ರಾಪ್ ಮಾಡಿ ಅಥವಾ ಚಿತ್ರ ಅಂಟಿಸಿ",
    pressCtrlV: "ಅಂಟಿಸಲು Ctrl+V ಒತ್ತಿ",
    chooseImage: "ಚಿತ್ರ ಆಯ್ಕೆಮಾಡಿ",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    analyzeDisease: "ರೋಗ ವಿಶ್ಲೇಷಿಸಿ",
    detectionResult: "ಪತ್ತೆ ಫಲಿತಾಂಶ",
    allPredictions: "ಎಲ್ಲಾ ಮುನ್ಸೂಚನೆಗಳು",
    recommendation: "ಶಿಫಾರಸು",
    recommendationText: "ಸರಿಯಾದ ಚಿಕಿತ್ಸೆಗಾಗಿ ತಕ್ಷಣ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    uploadToSeeResults: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ ನೋಡಲು ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    searchVetDoctors: "ಪಶುವೈದ್ಯರನ್ನು ಹುಡುಕಿ...",
    addVetDoctor: "ವೈದ್ಯರನ್ನು ಸೇರಿಸಿ",
    addNewVetDoctor: "ಹೊಸ ಪಶುವೈದ್ಯರ ನೋಂದಣಿ",
    vetRegisterBtn: "ವೈದ್ಯರನ್ನು ನೋಂದಾಯಿಸಿ",
    vetLoadingDoctors: "ವೈದ್ಯರನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    vetVerified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    loadErrorMsg: "ಡೇಟಾ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    vetClinicsComingSoon: "ಕ್ಲಿನಿಕ್ ನಿರ್ವಹಣೆ ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತಿದೆ",
    vetPatientsComingSoon: "ರೋಗಿ ನಿರ್ವಹಣೆ ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತಿದೆ",
    vetAppointmentsComingSoon: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನಿರ್ವಹಣೆ ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತಿದೆ",
    diseaseHealthy: "ಆರೋಗ್ಯವಂತ",
    diseaseCoccidiosis: "ರಕ್ತಭೇದಿ",
    diseaseNewCastle: "ನ್ಯೂಕ್ಯಾಸಲ್ ರೋಗ",
    diseaseSalmonella: "ಸಾಲ್ಮೊನೆಲ್ಲಾ",
  },
};

// For languages without specific translations, fall back to Hindi
const fallbackLangs = ['mr', 'gu', 'ml', 'or', 'pa'];
fallbackLangs.forEach(lang => {
  translations[lang] = translations['hi'];
});

const i18nDir = path.join(__dirname, 'src', 'i18n');

let totalUpdated = 0;
Object.keys(translations).forEach(lang => {
  const filePath = path.join(i18nDir, `${lang}.ts`);
  if (!fs.existsSync(filePath)) {
    console.log(`File ${lang}.ts not found, skipping.`);
    return;
  }

  let content = fs.readFileSync(filePath, 'utf8');
  const t = translations[lang];

  let newKeys = '';
  let updatedCount = 0;
  for (const [key, value] of Object.entries(t)) {
    // Check if key already exists in the file
    const keyRegex = new RegExp(`^\\s*${key}:\\s`, 'm');
    if (!keyRegex.test(content)) {
      newKeys += `  ${key}: ${JSON.stringify(value)},\n`;
      updatedCount++;
    }
  }

  if (newKeys) {
    // Insert before the closing };
    content = content.replace(/};\s*$/, `${newKeys}};`);
    fs.writeFileSync(filePath, content);
    console.log(`Updated ${lang}.ts — added ${updatedCount} keys`);
    totalUpdated += updatedCount;
  } else {
    console.log(`${lang}.ts — all keys already present`);
  }
});

console.log(`\nDone! Total new keys added: ${totalUpdated}`);
